In [11]:


# Gamestate Structure
# p1_hand    p1_board    p1_pitch_zone   p1_gy   p1_banish   ... p2_hand p2_board   p2_gy   p2_banish    combat_chain   active_player
# 1 (this is a card number as per its unique-id)
# 1
# 6
# 0
# nan       
# nan
# ...
# nan

# Card IDs
# 1     Wounding Blow R
# 3     Wounding Blow U
# 7     Brutal Assault R
# 8     Brutal Assault Y
# 9     Brutal Assault U
# Gamestate 1, before playing out brutal assault
import numpy as np
from scipy.sparse import block_diag, csr_matrix

# Convert submatrices to sparse format
hand_player_1_sparse = csr_matrix([[1, 3, 7, 9, 0, 0, 0, 0, 0, 0]])  # Example card IDs
hand_player_2_sparse = csr_matrix([[4, 5, 0, 0, 0, 0, 0, 0, 0, 0]])  # Example card IDs

# Example placeholders for other matrices in sparse format
board_player_1_sparse = csr_matrix(np.zeros((1, 5)))  # Example dimensions
board_player_2_sparse = csr_matrix(np.zeros((1, 5)))  # Example dimensions


# Life points can be included as sparse matrices too
life_player_1_sparse = csr_matrix([[40]])
life_player_2_sparse = csr_matrix([[40]])

ap_player_1_sparse = csr_matrix([[1]])
ap_player_2_sparse = csr_matrix([[0]])

pitch_player_1_sparse = csr_matrix([[0]])
pitch_player_2_sparse = csr_matrix([[0]])

gy_player_1_sparse = csr_matrix([[0]])
gy_player_2_sparse = csr_matrix([[0]])

# Construct the game state matrix in sparse format
game_state_matrix_sparse_1 = block_diag(
    [hand_player_1_sparse, life_player_1_sparse, board_player_1_sparse, ap_player_1_sparse, pitch_player_1_sparse, gy_player_1_sparse,
     hand_player_2_sparse, life_player_2_sparse, board_player_2_sparse, ap_player_2_sparse, pitch_player_2_sparse, gy_player_2_sparse,],
    format='csr'  # or any other preferred sparse format
)
game_state_matrix_sparse_1

<12x38 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [12]:
hand_player_1_sparse = csr_matrix([[1, 3, 0, 9, 0, 0, 0, 0, 0, 0]])  # Example card IDs
board_player_1_sparse = csr_matrix(np.zeros((1, 5)))  # Example dimensions

In [41]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io

public_titles = ['NTN-B', 'LFT', 'LTN', 'NTN-F', 'NTN-C']

dataframes = {}
for title in public_titles:
    url = f"https://www.anbima.com.br/informacoes/merc-sec/resultados/msec_28nov2023_{title.lower()}.asp"

    response = requests.get(url)

    from bs4 import BeautifulSoup
    import pandas as pd

    # Assuming 'html_content' is your HTML content
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find the table in your soup
    table = soup.find('table')

    # Use io.StringIO to wrap the HTML table string
    html_io = io.StringIO(str(table).replace('.', '').replace(',', '.'))

    # Read the table into a DataFrame
    df = pd.read_html(html_io)[2]

    # Now df is your DataFrame
    df.columns = df.iloc[4]

    # Drop the first two rows as they are now set as headers
    data = df.drop([0, 1, 2, 3, 4])

    # Optionally, reset the index if you want to start it from 0
    data = data.reset_index(drop=True)

    dataframes[title] = data

# Create an empty list to store the modified dataframes
modified_dataframes = []

# Iterate over each title and its corresponding dataframe
for title, df in dataframes.items():
    # Add a new column 'Title' to the dataframe
    df['Title'] = title
    # Append the modified dataframe to the list
    modified_dataframes.append(df)

# Concatenate all the dataframes in the list into one final dataframe
final_df = pd.concat(modified_dataframes, ignore_index=True)

# Assuming 'Title' is a column in your DataFrame
columns = ['Title'] + [col for col in final_df.columns if col != 'Title']
final_df = final_df[columns]
final_df

4,Title,Código SELIC,Data Base/Emissão,Data de Vencimento,Tx Compra,Tx Venda,Tx Indicativas,PU,Mínimo (D0),Máximo (D0),Mínimo (D+1),Máximo (D+1)
0,NTN-B,760199,15/07/2000,15/08/2024,6.5816,6.5468,6.5657,4218.739941,6.1003,7.2408,6.1308,7.2801
1,NTN-B,760199,15/07/2000,15/05/2025,5.8620,5.8349,5.8498,4183.391303,5.5381,6.1396,5.5406,6.1425
2,NTN-B,760199,15/07/2000,15/08/2026,5.5333,5.5057,5.5200,4282.016001,5.2651,5.7601,5.2688,5.7639
3,NTN-B,760199,15/07/2000,15/05/2027,5.5849,5.5547,5.5700,4228.980551,5.3222,5.8035,5.3130,5.7943
4,NTN-B,760199,15/07/2000,15/08/2028,5.5356,5.5073,5.5200,4315.698821,5.2788,5.7675,5.2688,5.7576
5,NTN-B,760199,15/07/2000,15/08/2030,5.5059,5.4763,5.4919,4353.038110,5.2825,5.7466,5.2601,5.7243
6,NTN-B,760199,15/07/2000,15/08/2032,5.5815,5.5463,5.5620,4358.889292,5.3767,5.8099,5.3486,5.7820
7,NTN-B,760199,15/07/2000,15/05/2033,5.6389,5.6089,5.6235,4288.575155,5.4524,5.8755,5.4158,5.8391
8,NTN-B,760199,15/07/2000,15/05/2035,5.6332,5.6012,5.6160,4310.176638,5.4611,5.8613,5.4210,5.8213
9,NTN-B,760199,15/07/2000,15/08/2040,5.7267,5.6824,5.7048,4369.171548,5.5656,5.9283,5.5302,5.8930
10,NTN-B,760199,15/07/2000,15/05/2045,5.7418,5.6993,5.7200,4322.091394,5.5933,5.9379,5.5552,5.8998
11,NTN-B,760199,15/07/2000,15/08/2050,5.7889,5.7568,5.7718,4369.629648,5.6480,5.9806,5.6135,5.9461
12,NTN-B,760199,15/07/2000,15/05/2055,5.7794,5.7457,5.7616,4324.560968,5.6421,5.9676,5.6072,5.9326
13,NTN-B,760199,15/07/2000,15/08/2060,5.7804,5.7481,5.7659,4390.035906,5.6493,5.9693,5.6144,5.9344
14,LFT,210100,01/07/2000,01/03/2024,0.0076,-0.0065,0.0004,14129.892972,-0.0279,0.0294,-0.0286,0.0299
15,LFT,210100,01/07/2000,01/09/2024,0.0029,0.0000,0.0012,14129.779932,-0.0349,0.0131,-0.0345,0.0141
16,LFT,210100,01/07/2000,01/03/2025,0.0066,0.0041,0.0055,14128.932137,-0.0135,0.0183,-0.0134,0.0201
17,LFT,210100,01/07/2000,01/09/2025,0.0231,0.0180,0.0204,14124.848590,0.0061,0.0485,0.0068,0.0496
18,LFT,210100,01/07/2000,01/03/2026,0.0451,0.0430,0.0442,14115.819570,0.0299,0.0834,0.0305,0.0843
19,LFT,210100,01/07/2000,01/09/2026,0.0880,0.0860,0.0870,14096.023550,0.0705,0.1035,0.0717,0.1033
20,LFT,210100,01/07/2000,01/03/2027,0.1255,0.1227,0.1240,14073.189598,0.0870,0.1404,0.0873,0.1406
21,LFT,210100,01/07/2000,01/09/2027,0.1453,0.1426,0.1442,14053.605527,0.1125,0.1597,0.1119,0.1604
22,LFT,210100,01/07/2000,01/03/2028,0.1494,0.1460,0.1474,14041.736393,0.1337,0.1706,0.1337,0.1706
23,LFT,210100,01/07/2000,01/09/2028,0.1630,0.1591,0.1614,14021.912114,0.1476,0.1796,0.1473,0.1799
24,LFT,210100,01/07/2000,01/03/2029,0.1731,0.1709,0.1720,14003.288877,0.1559,0.1823,0.1560,0.1824
25,LFT,210100,01/07/2000,01/09/2029,0.1755,0.1744,0.1750,13988.565499,0.1534,0.1871,0.1537,0.1873
26,LTN,100000,03/01/2020,01/01/2024,12.0312,12.0160,12.0236,989.690787,11.9098,12.2145,11.8929,12.2045
27,LTN,100000,07/01/2022,01/04/2024,11.3448,11.3166,11.3281,964.861700,11.2523,11.4550,11.2368,11.4369
28,LTN,100000,08/01/2021,01/07/2024,10.8980,10.8661,10.8818,941.524250,10.6954,11.0995,10.6888,11.0899
29,LTN,100000,08/07/2022,01/10/2024,10.5869,10.5636,10.5745,918.546494,10.3101,10.8560,10.3239,10.8688
30,LTN,100000,01/02/2018,01/01/2025,10.3886,10.3583,10.3745,897.177551,10.0852,10.7089,10.0981,10.7209
31,LTN,100000,06/01/2023,01/04/2025,10.3303,10.3161,10.3230,876.543142,10.0101,10.6908,10.0203,10.7002
32,LTN,100000,07/01/2022,01/07/2025,10.2523,10.2382,10.2450,856.903149,9.9030,10.6333,9.9126,10.6421
33,LTN,100000,07/07/2023,01/10/2025,10.2167,10.2029,10.2101,835.779030,9.8445,10.6217,9.8452,10.6217
34,LTN,100000,03/02/2020,01/01/2026,10.1703,10.1560,10.1630,815.814592,9.7740,10.5818,9.7746,10.5820
35,LTN,100000,06/01/2023,01/07/2026,10.2409,10.2281,10.2350,777.153261,9.8297,10.6652,9.8206,10.6560
36,LTN,100000,07/07/2023,01/07/2027,10.4451,10.4315,10.4372,700.653339,10.0640,10.9084,10.0052,10.8497
37,NTN-F,950199,10/01/2014,01/01/2025,10.4287,10.4068,10.4193,1034.984323,10.1331,10.7471,10.1470,10.7601
38,NTN-F,950199,15/01/2016,01/01/2027,10.2783,10.2477,10.2626,1032.907802,9.8755,10.7017,9.8456,10.6718
39,NTN-F,950199,05/01/2018,01/01/2029,10.6437,10.6306,10.6372,1016.970724,10.2945,11.1090,10.2216,11.0364
40,NTN-F,950199,10/01/2020,01/01/2031,10.8324,10.8144,10.8231,1002.363323,10.4922,11.2966,10.4109,11.2157
41,NTN-F,950199,07/01/2022,01/01/2033,10.9062,10.8950,10.9003,991.480274,10.5771,11.3681,10.4952,11.2868
42,NTN-C,770100,01/07/2000,01/01/2031,5.8089,5.4454,5.6990,8480.522210,5.2918,6.1681,5.2827,6.1605

In [38]:
final_df

4,Código SELIC,Data Base/Emissão,Data de Vencimento,Tx Compra,Tx Venda,Tx Indicativas,PU,Mínimo (D0),Máximo (D0),Mínimo (D+1),Máximo (D+1)
Title,,,,,,,,,,,
NTN-B,760199,15/07/2000,15/05/2025,5.8620,5.8349,5.8498,4183.391303,5.5381,6.1396,5.5406,6.1425
NTN-B,760199,15/07/2000,15/05/2027,5.5849,5.5547,5.5700,4228.980551,5.3222,5.8035,5.3130,5.7943
NTN-B,760199,15/07/2000,15/05/2033,5.6389,5.6089,5.6235,4288.575155,5.4524,5.8755,5.4158,5.8391
NTN-B,760199,15/07/2000,15/05/2035,5.6332,5.6012,5.6160,4310.176638,5.4611,5.8613,5.4210,5.8213
NTN-B,760199,15/07/2000,15/05/2045,5.7418,5.6993,5.7200,4322.091394,5.5933,5.9379,5.5552,5.8998
NTN-B,760199,15/07/2000,15/05/2055,5.7794,5.7457,5.7616,4324.560968,5.6421,5.9676,5.6072,5.9326
NTN-B,760199,15/07/2000,15/08/2024,6.5816,6.5468,6.5657,4218.739941,6.1003,7.2408,6.1308,7.2801
NTN-B,760199,15/07/2000,15/08/2026,5.5333,5.5057,5.5200,4282.016001,5.2651,5.7601,5.2688,5.7639
NTN-B,760199,15/07/2000,15/08/2028,5.5356,5.5073,5.5200,4315.698821,5.2788,5.7675,5.2688,5.7576
NTN-B,760199,15/07/2000,15/08/2030,5.5059,5.4763,5.4919,4353.038110,5.2825,5.7466,5.2601,5.7243
NTN-B,760199,15/07/2000,15/08/2032,5.5815,5.5463,5.5620,4358.889292,5.3767,5.8099,5.3486,5.7820
NTN-B,760199,15/07/2000,15/08/2040,5.7267,5.6824,5.7048,4369.171548,5.5656,5.9283,5.5302,5.8930
NTN-B,760199,15/07/2000,15/08/2050,5.7889,5.7568,5.7718,4369.629648,5.6480,5.9806,5.6135,5.9461
NTN-B,760199,15/07/2000,15/08/2060,5.7804,5.7481,5.7659,4390.035906,5.6493,5.9693,5.6144,5.9344
LFT,210100,01/07/2000,01/03/2024,0.0076,-0.0065,0.0004,14129.892972,-0.0279,0.0294,-0.0286,0.0299
LFT,210100,01/07/2000,01/03/2025,0.0066,0.0041,0.0055,14128.932137,-0.0135,0.0183,-0.0134,0.0201
LFT,210100,01/07/2000,01/03/2026,0.0451,0.0430,0.0442,14115.819570,0.0299,0.0834,0.0305,0.0843
LFT,210100,01/07/2000,01/03/2027,0.1255,0.1227,0.1240,14073.189598,0.0870,0.1404,0.0873,0.1406
LFT,210100,01/07/2000,01/03/2028,0.1494,0.1460,0.1474,14041.736393,0.1337,0.1706,0.1337,0.1706
LFT,210100,01/07/2000,01/03/2029,0.1731,0.1709,0.1720,14003.288877,0.1559,0.1823,0.1560,0.1824
LFT,210100,01/07/2000,01/09/2024,0.0029,0.0000,0.0012,14129.779932,-0.0349,0.0131,-0.0345,0.0141
LFT,210100,01/07/2000,01/09/2025,0.0231,0.0180,0.0204,14124.848590,0.0061,0.0485,0.0068,0.0496
LFT,210100,01/07/2000,01/09/2026,0.0880,0.0860,0.0870,14096.023550,0.0705,0.1035,0.0717,0.1033
LFT,210100,01/07/2000,01/09/2027,0.1453,0.1426,0.1442,14053.605527,0.1125,0.1597,0.1119,0.1604
LFT,210100,01/07/2000,01/09/2028,0.1630,0.1591,0.1614,14021.912114,0.1476,0.1796,0.1473,0.1799
LFT,210100,01/07/2000,01/09/2029,0.1755,0.1744,0.1750,13988.565499,0.1534,0.1871,0.1537,0.1873
LTN,100000,03/01/2020,01/01/2024,12.0312,12.0160,12.0236,989.690787,11.9098,12.2145,11.8929,12.2045
LTN,100000,01/02/2018,01/01/2025,10.3886,10.3583,10.3745,897.177551,10.0852,10.7089,10.0981,10.7209
LTN,100000,03/02/2020,01/01/2026,10.1703,10.1560,10.1630,815.814592,9.7740,10.5818,9.7746,10.5820
LTN,100000,07/01/2022,01/04/2024,11.3448,11.3166,11.3281,964.861700,11.2523,11.4550,11.2368,11.4369
LTN,100000,06/01/2023,01/04/2025,10.3303,10.3161,10.3230,876.543142,10.0101,10.6908,10.0203,10.7002
LTN,100000,08/01/2021,01/07/2024,10.8980,10.8661,10.8818,941.524250,10.6954,11.0995,10.6888,11.0899
LTN,100000,07/01/2022,01/07/2025,10.2523,10.2382,10.2450,856.903149,9.9030,10.6333,9.9126,10.6421
LTN,100000,06/01/2023,01/07/2026,10.2409,10.2281,10.2350,777.153261,9.8297,10.6652,9.8206,10.6560
LTN,100000,07/07/2023,01/07/2027,10.4451,10.4315,10.4372,700.653339,10.0640,10.9084,10.0052,10.8497
LTN,100000,08/07/2022,01/10/2024,10.5869,10.5636,10.5745,918.546494,10.3101,10.8560,10.3239,10.8688
LTN,100000,07/07/2023,01/10/2025,10.2167,10.2029,10.2101,835.779030,9.8445,10.6217,9.8452,10.6217
NTN-F,950199,10/01/2014,01/01/2025,10.4287,10.4068,10.4193,1034.984323,10.1331,10.7471,10.1470,10.7601
NTN-F,950199,15/01/2016,01/01/2027,10.2783,10.2477,10.2626,1032.907802,9.8755,10.7017,9.8456,10.6718
NTN-F,950199,05/01/2018,01/01/2029,10.6437,10.6306,10.6372,1016.970724,10.2945,11.1090,10.2216,11.0364
NTN-F,950199,10/01/2020,01/01/2031,10.8324,10.8144,10.8231,1002.363323,10.4922,11.2966,10.4109,11.2157
NTN-F,950199,07/01/2022,01/01/2033,10.9062,10.8950,10.9003,991.480274,10.5771,11.3681,10.4952,11.2868
NTN-C,770100,01/07/2000,01/01/2031,5.8089,5.4454,5.6990,8480.522210,5.2918,6.1681,5.2827,6.1605

In [15]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io


url = "https://www4.bcb.gov.br/pom/demab/negociacoes/NegTFMS_ExibeDP.asp?data=20231128&grupo=T&periodo=S&idpai=&idioma=P&frame=1"

response = requests.get(url)


# Assuming 'html_content' is your HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table in your soup
table = soup.find_all('table')

In [16]:
# Use io.StringIO to wrap the HTML table string
html_io = io.StringIO(str(table).replace('.', '').replace(',', '.'))

# Read the table into a DataFrame
df = pd.read_html(html_io)
df[1]

           Data Características do Título                                    \
           Data                     Sigla  Código   Código ISIN     Emissão
0    27/11/2023                       LFT  210100  BRSTNCLF1RA8  05/01/2018
1    27/11/2023                       LFT  210100  BRSTNCLF0008  06/07/2018
2    27/11/2023                       LFT  210100  BRSTNCLF1RC4  26/10/2018
3    27/11/2023                       LFT  210100  BRSTNCLF1RD2  08/03/2019
4    27/11/2023                       LFT  210100  BRSTNCLF1RE0  06/09/2019
..          ...                       ...     ...           ...         ...
100  28/11/2023                     NTN-F  950199  BRSTNCNTF1P8  15/01/2016
101  28/11/2023                     NTN-F  950199  BRSTNCNTF1Q6  05/01/2018
102  28/11/2023                     NTN-F  950198  BRSTNCNTF1Y0  01/10/2019
103  28/11/2023                     NTN-F  950199  BRSTNCNTF204  10/01/2020
104  28/11/2023                     NTN-F  950199  BRSTNCNTF212  07/01/2022

                Nº de Operações                   Quantidade Negociada  \
     Vencimento           Total Com Cor-  retagem                Total
0    01/03/2024             155                33                56016
1    01/09/2024             191                51               204160
2    01/03/2025              83                18                55797
3    01/09/2025             108                34                77849
4    01/03/2026             221                38                76732
..          ...             ...               ...                  ...
100  01/01/2027              31                 1                42225
101  01/01/2029              55                 3               842710
102  01/01/2029               1                 0                  839
103  01/01/2031              41                 2               287733
104  01/01/2033              65                 8               504597

                      Preços de Negociação                              \
    Com Cor-  retagem               Mínimo         Médio        Máximo
0               22659         14118.126279  14123.471033  14132.955947
1               71827         14078.227411  14123.335102  14129.439197
2                2369         14114.877876  14122.905274  14133.181923
3               31646         13987.681696  14118.820443  14132.701724
4                5155         14060.756650  14109.725918  14127.165315
..                ...                  ...           ...           ...
100                24          1016.744373   1031.078542   1044.542820
101            100024          1000.713947   1013.060389   1034.520340
102                 0           583.999078    583.999078    583.999078
103             50008           980.810875    997.892097   1029.369575
104            257496           967.432614    985.924978   1012.641550

    Preços de Referência                          Taxas de Negociação          \
                  Lastro Valor nominal atualizado              Mínima   Média
0           14120.576661             14123.493207             -0.2589  0.0007
1           14114.845872             14123.493207             -0.0548  0.0015
2           14108.657304             14123.493207             -0.0539  0.0033
3           14099.263690             14123.493207             -0.0369  0.0187
4           14084.246501             14123.493207             -0.0114  0.0431
..                   ...                      ...                 ...     ...
100          1017.460582              1000.000000                 NaN     NaN
101           993.211142              1000.000000                 NaN     NaN
102           578.919636              1000.000000                 NaN     NaN
103           971.309726              1000.000000                 NaN     NaN
104           953.631731              1000.000000                 NaN     NaN


     Máxima
0    0.1478
1    0.4201
2    0.0481
3    0.5499
4    0.1970
..      ...
100     NaN
101     NaN
102     NaN
103     NaN
104     NaN

[105 rows x 18 columns]